---

- name: create tomcat directory
  file:
    path: /srv/tomcat
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create temporary tomcat directory
  file: 
    path: '{{ temp_dir.tomcat }}'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode : 07555

- name: create artefacts directory 
  file:
    path: /srv/artefacts
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create {{ tomact_instance_name }} directory in tomcat 
  file: 
    path: '{{ tomcat_source_url }}'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0755

- name: Download Tomcat
  get_url:
    url: '{{ tomcat_source_url }}'
    dest: '{{ temp_dir.tomcat }}/tomcat.tar.gz'

- name: Extracting Tomcat archive
  unarchive: 
   src: '{{ temp_dir.tomcat }}/apache-tomcat/'
   dest: '/srv/tomcat/{{ tomcat_instance_name }}/'
   owner: '{{ user_name }}'
   group: '{{ user_name }}'

- name: Copying tomcat directory to location 
  copy: 
    src: '{{temp_dir.tomcat}}/apache-tomcat-8.5.66-src/'
    dest: '/srv/tomcat/{{tomcat_instance_name}}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'

- name: Recursively change owership of a directory
  file: 
    path: '{{ item }}'
    state: file
    owner: '{{ user_name }}'
    group: ' {{ user_name }}'
    mode: 0755

  loop:
    - "{{ tomcat_cataline_base }}/bin/version"
    - "{{ tomcat_cataline_base }}/bin/tool-wrapper.sh"
    - "{{ tomcat_cataline_base }}/bin/startup.sh"
    - "{{ tomcat_cataline_base }}/bin/shutdown.sh"
    - "{{ tomcat_cataline_base }}/bin/setclasspath.sh"
    - "{{ tomcat_cataline_base }}/bin/daemon.sh"
    - "{{ tomcat_cataline_base }}/bin/configtest.sh"
    - "{{ tomcat_cataline_base }}/bin/catalina.sh"

- name: Change ownership of logs
  file:
    path: '{{ tomcat_catalina_base }}/logs'
    state: directory
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    mode: 0755 
